global:
  imageTag: sha-71305c25819adf341c3d6d37136e8ec72e56973b

gateway:
  loadBalancerIP: 10.80.30.204
  addressPool: pve-dev-services

externalSecrets:
  vaultServer: https://10.80.0.13:8200
  runtimePath: apps/dentistdss/dev/runtime

commonEnv:
  JAVA_TOOL_OPTIONS: -Xms64m -XX:MaxRAMPercentage=50.0 -XX:+ExitOnOutOfMemoryError

deploymentStrategy:
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

javaResources:
  requests:
    memory: 384Mi
  limits:
    memory: 768Mi

services:
  api-gateway:
    replicas: 1
