global:
  imageTag: bootstrap

gateway:
  loadBalancerIP: 10.80.20.204
  addressPool: pve-prod-services

externalSecrets:
  vaultServer: https://10.80.0.13:8200
  runtimePath: apps/dentistdss/prod/runtime
  genaiServiceAuthPath: apps/dentistdss/prod/genai-service-auth
