global:
  imageTag: sha-84d86a563c897bfcc58d1a848c594e70070a613c

gateway:
  loadBalancerIP: 10.80.30.204
  addressPool: pve-dev-services

externalSecrets:
  runtimePath: apps/dentistdss/dev/runtime

services:
  api-gateway:
    replicas: 1
