-- V1__baseline.sql
--
-- Baseline schema for the shared dentistdss PostgreSQL database. It captures
-- the schema that Hibernate ddl-auto=update has been creating from the current
-- JPA entities across auth-service, clinic-service, user-profile-service,
-- appointment-service, clinical-records-service, notification-service, and
-- system-service, plus the native enum types those services require (which
-- ddl-auto=update cannot create and which existing installations created
-- out-of-band).
--
-- This file is IMMUTABLE once committed. Existing installations adopt it
-- non-destructively through Flyway baseline-on-migrate (V1 is skipped, their
-- schema is untouched); fresh installations get it applied. Future schema
-- changes MUST be added as new V2__*.sql migrations in this module, never as
-- edits here.

-- Native PostgreSQL enum types. Created before the tables that use them.
create type appointment_status as enum ('REQUESTED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'RESCHEDULED');
create type urgency_level as enum ('ROUTINE', 'MODERATE', 'URGENT', 'EMERGENCY');
create type notification_type as enum ('EMAIL', 'SMS', 'PUSH', 'IN_APP');
create type notification_status as enum ('PENDING', 'SENT', 'FAILED', 'READ');

-- Sequences for @SequenceGenerator entities (allocationSize = 1 -> increment 1).
-- clinics.id is a plain identity column: both auth-service and clinic-service
-- map it as IDENTITY, and no identity column may name its backing sequence
-- (Hibernate's PostgreSQL metadata extraction cannot see identity-owned
-- sequences, which would fail ddl-auto=validate at boot).
create sequence user_id_seq start with 1000000 increment by 1;
create sequence appointment_id_seq start with 10000 increment by 1;
create sequence patient_record_id_seq start with 5000 increment by 1;
create sequence notification_id_seq start with 1 increment by 1;

-- ---------------------------------------------------------------------------
-- auth-service / user-profile-service: users (superset of both mappings)
-- ---------------------------------------------------------------------------
create table users (
    id bigint not null,
    email varchar(255) not null,
    password varchar(255),
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    phone varchar(20),
    date_of_birth date,
    address text,
    provider varchar(255),
    provider_id varchar(255),
    profile_picture_url varchar(500),
    email_verified boolean not null,
    email_verification_token varchar(255),
    email_verification_token_expiry timestamp(6),
    phone_verified boolean,
    verification_code varchar(255),
    verification_code_expiry timestamp(6),
    approval_status varchar(255),
    approval_rejection_reason varchar(255),
    approved_by varchar(255),
    approval_date timestamp(6),
    enabled boolean not null,
    security_version bigint default 1 not null,
    account_non_expired boolean not null,
    credentials_non_expired boolean not null,
    account_non_locked boolean not null,
    last_login_at timestamp(6),
    clinic_id bigint,
    clinic_name varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uk_users_email unique (email)
);

create table user_roles (
    user_id bigint not null,
    role varchar(255),
    constraint uq_user_roles_user_id unique (user_id),
    constraint fk_user_roles_user foreign key (user_id) references users (id)
);

-- ---------------------------------------------------------------------------
-- auth-service / clinic-service: clinics (superset of both mappings)
-- ---------------------------------------------------------------------------
create table clinics (
    id bigint generated by default as identity,
    name varchar(255),
    address varchar(255),
    city varchar(255),
    state varchar(255),
    zip_code varchar(255),
    country varchar(255),
    phone_number varchar(255),
    email varchar(255),
    website varchar(255),
    tax_id varchar(255),
    license_number varchar(255),
    established_date date,
    description varchar(255),
    logo_url varchar(255),
    enabled boolean,
    approved boolean,
    approval_by bigint,
    approval_date timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uk_clinics_name unique (name)
);

create table clinic_admin (
    clinic_id bigint,
    admin_id bigint,
    constraint uq_clinic_admin_clinic unique (clinic_id),
    constraint uq_clinic_admin_admin unique (admin_id),
    constraint fk_clinic_admin_clinic foreign key (clinic_id) references clinics (id),
    constraint fk_clinic_admin_admin foreign key (admin_id) references users (id)
);

-- ---------------------------------------------------------------------------
-- auth-service / user-profile-service: user approval requests
-- ---------------------------------------------------------------------------
create table user_approval_requests (
    id integer generated by default as identity,
    user_id bigint not null,
    requested_role varchar(255) not null,
    clinic_id bigint,
    status varchar(255),
    request_reason text,
    supporting_documents text[],
    reviewed_by bigint,
    review_notes text,
    reviewed_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

-- ---------------------------------------------------------------------------
-- auth-service: refresh-token session families and the security outbox
-- ---------------------------------------------------------------------------
create table auth_sessions (
    id bigint generated by default as identity,
    user_id bigint not null,
    family_id varchar(36) not null,
    security_version bigint not null,
    token_hash varchar(64) not null,
    replaced_by_hash varchar(64),
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    revoked_at timestamp(6),
    primary key (id),
    constraint uk_auth_sessions_token_hash unique (token_hash)
);
create index idx_auth_sessions_user_id on auth_sessions (user_id);
create index idx_auth_sessions_family_id on auth_sessions (family_id);

create table auth_security_outbox (
    id bigint generated by default as identity,
    user_id bigint not null,
    family_id varchar(36) not null,
    tombstone_ttl_millis bigint not null,
    created_at timestamp(6) not null,
    last_attempt_at timestamp(6),
    attempts integer not null,
    last_error varchar(512),
    expires_at timestamp(6) not null,
    primary key (id),
    constraint uk_auth_security_outbox_family unique (user_id, family_id)
);
create index idx_auth_security_outbox_pending on auth_security_outbox (expires_at, last_attempt_at);

-- ---------------------------------------------------------------------------
-- user-profile-service: patients, profiles, medical history
-- ---------------------------------------------------------------------------
create table patients (
    id bigint not null,
    first_name varchar(255),
    last_name varchar(255),
    date_of_birth date,
    email varchar(255),
    phone_number varchar(255),
    address varchar(255),
    health_history text,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table patient_profiles (
    id integer generated by default as identity,
    user_id bigint not null,
    emergency_contact_name varchar(255),
    emergency_contact_phone varchar(255),
    emergency_contact_relationship varchar(255),
    insurance_provider varchar(255),
    insurance_policy_number varchar(255),
    insurance_group_number varchar(255),
    blood_type varchar(10),
    allergies varchar(255),
    current_medications text,
    medical_conditions text,
    preferred_pharmacy varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uk_patient_profiles_user_id unique (user_id)
);

create table medical_history (
    id integer generated by default as identity,
    patient_id bigint not null,
    condition_name varchar(255) not null,
    description text,
    diagnosed_date date,
    resolved_date date,
    is_chronic boolean,
    medications text,
    notes text,
    created_by bigint,
    created_at timestamp(6),
    primary key (id)
);

-- ---------------------------------------------------------------------------
-- clinic-service: bookable services
-- ---------------------------------------------------------------------------
create table services (
    id integer generated by default as identity,
    clinic_id bigint not null,
    name varchar(255) not null,
    description text,
    duration_minutes integer,
    price numeric(10,2),
    category varchar(255),
    is_active boolean,
    created_at timestamp(6),
    primary key (id)
);

-- ---------------------------------------------------------------------------
-- appointment-service: appointments and dentist availability
-- ---------------------------------------------------------------------------
create table appointments (
    id bigint not null,
    patient_id bigint not null,
    dentist_id bigint not null,
    clinic_id bigint not null,
    service_id integer,
    appointment_date date not null,
    start_time time(6) not null,
    end_time time(6) not null,
    status appointment_status,
    reason_for_visit text,
    symptoms text,
    urgency urgency_level,
    ai_triage_notes text,
    notes text,
    created_by bigint,
    confirmed_by bigint,
    cancelled_by bigint,
    cancellation_reason text,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table dentist_availability (
    id integer generated by default as identity,
    dentist_id bigint not null,
    clinic_id bigint not null,
    available_date date not null,
    start_time time(6) not null,
    end_time time(6) not null,
    is_blocked boolean,
    block_reason varchar(255),
    created_at timestamp(6),
    primary key (id),
    constraint uk_dentist_availability_slot unique (dentist_id, clinic_id, available_date, start_time)
);

-- ---------------------------------------------------------------------------
-- clinical-records-service: notes, images, visits, treatment plans
-- ---------------------------------------------------------------------------
create table clinical_notes (
    id bigint not null,
    appointment_id bigint,
    patient_id bigint not null,
    dentist_id bigint not null,
    clinic_id bigint not null,
    visit_id bigint,
    chief_complaint text,
    examination_findings text,
    diagnosis text,
    treatment_performed text,
    treatment_plan text,
    prescriptions text,
    follow_up_instructions text,
    ai_assisted_notes text,
    attachments text[],
    category varchar(255),
    is_draft boolean,
    version integer,
    parent_note_id bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    signed_at timestamp(6),
    signed_by bigint,
    primary key (id)
);

create table dental_images (
    id bigint generated by default as identity,
    patient_id bigint not null,
    dentist_id bigint not null,
    clinic_id bigint not null,
    clinical_note_id bigint,
    visit_id bigint,
    gridfs_file_id varchar(255) not null,
    thumbnail_gridfs_id varchar(255),
    original_filename varchar(255),
    content_type varchar(255),
    file_size bigint,
    image_type varchar(255),
    tooth_number varchar(255),
    description text,
    tags text,
    is_primary boolean,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table service_visits (
    id bigint generated by default as identity,
    patient_id bigint not null,
    dentist_id bigint not null,
    clinic_id bigint not null,
    appointment_id bigint,
    visit_type varchar(255),
    visit_date timestamp(6) not null,
    check_in_time timestamp(6),
    check_out_time timestamp(6),
    duration_minutes integer,
    status varchar(255),
    notes text,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table treatment_plans (
    id integer generated by default as identity,
    patient_id bigint not null,
    dentist_id bigint not null,
    clinic_id bigint not null,
    plan_name varchar(255),
    description text,
    total_cost numeric(10,2),
    insurance_coverage numeric(10,2),
    patient_cost numeric(10,2),
    status varchar(50),
    version integer,
    parent_plan_id integer,
    created_at timestamp(6),
    accepted_at timestamp(6),
    completed_at timestamp(6),
    primary key (id)
);

create table treatment_plan_items (
    id integer generated by default as identity,
    treatment_plan_id integer not null,
    service_id integer,
    tooth_number varchar(10),
    description text,
    cost numeric(10,2),
    status varchar(50),
    sequence_order integer,
    notes text,
    primary key (id),
    constraint fk_treatment_plan_items_plan foreign key (treatment_plan_id) references treatment_plans (id)
);

-- ---------------------------------------------------------------------------
-- notification-service: notifications and templates
-- ---------------------------------------------------------------------------
create table notifications (
    id bigint not null,
    user_id bigint not null,
    template_id integer,
    type notification_type not null,
    subject varchar(255),
    body text not null,
    status notification_status,
    scheduled_for timestamp(6),
    sent_at timestamp(6),
    read_at timestamp(6),
    metadata jsonb,
    created_at timestamp(6),
    primary key (id)
);

create table notification_templates (
    id integer generated by default as identity,
    name varchar(255) not null,
    type notification_type not null,
    subject varchar(255),
    body_template text not null,
    variables text[],
    is_active boolean,
    created_at timestamp(6),
    primary key (id),
    constraint uk_notification_templates_name unique (name)
);

-- ---------------------------------------------------------------------------
-- system-service: system settings
-- ---------------------------------------------------------------------------
create table system_settings (
    id bigint generated by default as identity,
    key varchar(255) not null,
    value text not null,
    description varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uk_system_settings_key unique (key)
);
