-- ---------------------------------------------------------------------------
-- auth-service: durable audit event outbox (AUDIT-01)
--
-- A row is written in the same transaction as the security-critical mutation
-- it records, so the event exists if and only if the mutation committed. The
-- scheduled relay delivers rows to audit-service and deletes them only after
-- a confirmed delivery. Rows are never expired or purged: an undeliverable
-- event is retried with backoff until it succeeds.
-- ---------------------------------------------------------------------------
create table auth_audit_outbox (
    id bigint generated by default as identity,
    action varchar(100) not null,
    target varchar(255),
    asserted_user_id bigint,
    asserted_clinic_id bigint,
    context jsonb,
    created_at timestamp(6) not null,
    last_attempt_at timestamp(6),
    attempts integer not null,
    last_error varchar(512),
    primary key (id)
);
create index idx_auth_audit_outbox_pending on auth_audit_outbox (created_at);
